import type { User } from './types';

export const MOCK_DISCOVER_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Катя',
    age: 20,
    gender: 'female',
    housingType: 'dormitory',
    university: 'КФУ',
    faculty: 'Институт ИТИС',
    course: '2 курс',
    location: 'Деревня Универсиады, корпус 3',
    district: 'Приволжский район',
    bio: 'Ищу спокойную соседку. Учусь, люблю порядок и тихие вечера.',
    interests: ['Учёба', 'Спорт', 'Кино'],
    habits: {
      sleepSchedule: 'early_bird',
      cleanliness: 'high',
      noiseLevel: 'quiet',
      guestFrequency: 'rarely',
      petPreference: 'no_pets',
      smokingPreference: 'no',
      alcoholPreference: 'no',
      roomOrderPreference: 'strict',
      quietTime: {
        from: '23:00',
        to: '08:00',
      },
    },
    budget: {
      min: 20,
      max: 35,
      currency: '₽',
      period: 'month',
    },
    moveInDate: 'любая',
    stayDuration: '6-12 months',
    idealRoommateDescription:
      'Спокойная соседка без частых гостей, которая уважает тишину и любит порядок.',
    rentalCriteria:
      '1-2 комнаты, базовая мебель, рабочий стол, нормальная кухня и стиральная машина.',
    avatar: '',
    photos: [],
    isSmokingAllowed: false,
    hasPets: false,
    hasQuietHours: true,
    verified: false,
    compatibilityNote: 'Подойдёт тем, кто ценит тишину, чистоту и спокойный бытовой ритм.',
  },
  {
    id: 'user-2',
    name: 'Данил',
    age: 22,
    gender: 'male',
    housingType: 'rental',
    university: 'КНИТУ-КАИ',
    faculty: 'Институт радиоэлектроники и телекоммуникаций',
    course: '4 курс',
    location: 'Съём у Аметьево',
    district: 'Советский район',
    bio: 'Ищу соседа без лишней драмы. Нравится, когда дома уютно и спокойно.',
    interests: ['Бег', 'Кофе', 'Сериалы'],
    habits: {
      sleepSchedule: 'flexible',
      cleanliness: 'medium',
      noiseLevel: 'moderate',
      guestFrequency: 'sometimes',
      petPreference: 'no_pets',
      smokingPreference: 'outside_only',
      alcoholPreference: 'socially',
      roomOrderPreference: 'balanced',
    },
    budget: {
      min: 24,
      max: 38,
      currency: '₽',
      period: 'month',
    },
    moveInDate: 'с 15 августа',
    stayDuration: '12+ months',
    idealRoommateDescription:
      'Адекватный сосед без конфликтов, который соблюдает бытовые договорённости.',
    rentalCriteria: 'Съёмная квартира с мебелью, интернетом и отдельным местом для учёбы.',
    avatar: '/mock/users/danil/avatar.jpg',
    photos: ['/mock/users/danil/1.jpg', '/mock/users/danil/2.jpg'],
    isSmokingAllowed: true,
    hasPets: false,
    hasQuietHours: false,
    verified: true,
    compatibilityNote: 'Нормально относится к активному ритму, но без шума по ночам.',
  },
  {
    id: 'user-3',
    name: 'Мила',
    age: 21,
    gender: 'female',
    housingType: 'dormitory',
    university: 'КГЭУ',
    faculty: 'Институт электроэнергетики и электроники',
    course: '3 курс',
    location: 'Общежитие КГЭУ №2',
    district: 'Вахитовский район',
    bio: 'Люблю уют, готовку и спокойные вечера дома. Ищу доброжелательного соседа.',
    interests: ['Готовка', 'Книги', 'Прогулки'],
    habits: {
      sleepSchedule: 'early_bird',
      cleanliness: 'high',
      noiseLevel: 'quiet',
      guestFrequency: 'never',
      petPreference: 'has_pets',
      smokingPreference: 'no',
      alcoholPreference: 'rarely',
      roomOrderPreference: 'strict',
      quietTime: {
        from: '23:00',
        to: '07:30',
      },
    },
    budget: {
      min: 22,
      max: 32,
      currency: '₽',
      period: 'month',
    },
    moveInDate: 'с 10 сентября',
    stayDuration: '6-12 months',
    idealRoommateDescription:
      'Доброжелательный человек, который любит спокойную домашнюю атмосферу.',
    rentalCriteria: 'Уютная квартира с мебелью, чистой кухней и возможностью жить с питомцем.',
    avatar: '/mock/users/mila/avatar.jpg',
    photos: ['/mock/users/mila/1.jpg', '/mock/users/mila/2.jpg'],
    isSmokingAllowed: false,
    hasPets: true,
    hasQuietHours: true,
    verified: false,
    compatibilityNote: 'Хороший вариант для тех, кто любит спокойный домашний ритм.',
  },
  {
    id: 'user-4',
    name: 'Лев',
    age: 23,
    gender: 'male',
    housingType: 'rental',
    university: 'КНИТУ',
    faculty: 'Факультет информационных технологий',
    course: '4 курс',
    location: 'Съём у Козьей Слободы',
    district: 'Ново-Савиновский район',
    bio: 'Нужен адекватный сосед, который уважает личное пространство и общие правила.',
    interests: ['Спортзал', 'Подкасты', 'Настолки'],
    habits: {
      sleepSchedule: 'night_owl',
      cleanliness: 'medium',
      noiseLevel: 'social',
      guestFrequency: 'often',
      petPreference: 'pet_friendly',
      smokingPreference: 'outside_only',
      alcoholPreference: 'yes',
      roomOrderPreference: 'flexible',
    },
    budget: {
      min: 28,
      max: 45,
      currency: '₽',
      period: 'month',
    },
    moveInDate: 'с 1 октября',
    stayDuration: '3-6 months',
    idealRoommateDescription:
      'Самостоятельный сосед, который уважает личное пространство и не драматизирует.',
    rentalCriteria:
      'Квартира на 1-2 комнаты, нормальный ремонт, мебель и удобная транспортная доступность.',
    avatar: '/mock/users/lev/avatar.jpg',
    photos: ['/mock/users/lev/1.jpg', '/mock/users/lev/2.jpg'],
    isSmokingAllowed: true,
    hasPets: false,
    hasQuietHours: false,
    verified: true,
    compatibilityNote: 'Больше подойдёт тем, кто не любит слишком строгие ограничения.',
  },
];

export const MOCK_DETAILED_USER: User = {
  ...MOCK_DISCOVER_USERS[0],
  bio: 'Ищу соседку или соседа для спокойного совместного проживания. Важно, чтобы дома было чисто, без внезапных шумных компаний, с понятными правилами по уборке и уважением к личному пространству. Люблю тихие вечера, музыку в наушниках и уютную атмосферу.',
  interests: ['Кино', 'Йога', 'Музыка', 'Кофейни', 'Прогулки', 'Фотография'],
  photos: ['/mock/users/alina/1.jpg', '/mock/users/alina/2.jpg', '/mock/users/alina/3.jpg'],
  idealRoommateDescription:
    'Спокойный сосед, который уважает границы, умеет договариваться и не устраивает шумных посиделок дома.',
  rentalCriteria:
    'Нужна квартира с мебелью, местом для хранения вещей, нормальной кухней и удобным районом рядом с транспортом.',
};

export const MOCK_EMPTY_DISCOVER_USERS: User[] = [];
