export const RoutePaths = {
  LANDING: '/',
  AUTH: '/auth',
  LOGIN: '/login',
  REGISTER: '/register',
  DISCOVER: '/discover',
  MATCHES: '/matches',
  CHATS: '/chats',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  VERIFY_EMAIL: '/auth/verify-email',
  VERIFY_CODE: '/auth/verify-code',
  SUCCESS: '/auth/success',
  ERROR: '/auth/error',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  ONBOARDING: '/onboarding',
  ONBOARDING_STEP_1: '/onboarding/step-1',
  ONBOARDING_STEP_2: '/onboarding/step-2',
  ONBOARDING_STEP_3: '/onboarding/step-3',
  ONBOARDING_STEP_4: '/onboarding/step-4',
  ADMIN_REPORTS: '/admin/reports',
  NOT_FOUND: '*',
  REPORT: '/report',
};
