export const RoutePaths = {
  LANDING: '/',
  AUTH: '/auth',
  DISCOVER: '/discover',
  MATCHES: '/matches',
  CHATS: '/chats',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  VERIFY_EMAIL: '/verify-email',
  VERIFY_CODE: '/verify-code',
  SUCCESS: '/success',
  ERROR: '/error',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  ONBOARDING: '/onboarding',
  ONBOARDING_STEP_1: '/onboarding/step-1',
  ONBOARDING_STEP_2: '/onboarding/step-2',
  ONBOARDING_STEP_3: '/onboarding/step-3',
  ONBOARDING_STEP_4: '/onboarding/step-4',
  NOT_FOUND: '*',
};
