export const RoutePaths = {
  LANDING: '/',
  AUTH: '/auth',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  DISCOVER: '/discover',
  MATCHES: '/matches',
  CHATS: '/chats',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  VERIFY_EMAIL: '/auth/verify-email',
  VERIFY_CODE: '/auth/verify-code',
  SUCCESS: '/auth/success',
  ERROR: '/auth/error',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  ONBOARDING: '/onboarding',
  ONBOARDING_STEP_1: '/onboarding/step-1',
  ONBOARDING_STEP_2: '/onboarding/step-2',
  ONBOARDING_STEP_3: '/onboarding/step-3',
  ONBOARDING_STEP_4: '/onboarding/step-4',
  ONBOARDING_SUMMARY: '/onboarding/summary',
  ONBOARDING_SUCCESS: '/onboarding/success',
  FILTERS: '/discover/filters',
  USER_PROFILE_BASE: '/user-profile',
  ADMIN_REPORTS: '/admin/reports',
  REPORT: '/report',
  NOT_FOUND: '*',
  reportByUser: (userId: string): string => `/report/${userId}`,
  userProfile: (userId: string): string => `/user-profile/${userId}`,
};
